### ISSUE TITLE
Change Schnorrkel signing context from 'substrate' to 'doughnut'

### ISSUE THREAD

**Issue by wilfred-centrality** [cennznet/doughnut-rs#11]
Dependant on:
* https://github.com/cennznet/doughnut-maker/issues/1
* https://github.com/paritytech/schnorrkel-js/issues/12

**Comment by elim0322** [comment]
Bumping up schnorrkel dependency to `version = "0.8.5"` resulted in test fails & broke this line: https://github.com/cennznet/doughnut-rs/blob/master/src/signature/mod.rs#L66

**Comment by holygits** [comment]
closed via #58
