### ISSUE TITLE
Support signing method 1 (Ed25519) in Rust

### ISSUE THREAD

**Issue by wilfred-centrality** [cennznet/doughnut-rs#2]
Implementation tasks:
- [ ] Handle ed25519 signature in codec
- [ ] Add a verify function to DoughnutAPI trait for signature check

https://github.com/cennznet/doughnut-paper/blob/master/format.md#1

**Comment by holygits** [comment]
The rust codec doesn't do any signing or verification currently.  
We can add a cli tool to sign doughnuts but there's no use case for this at the moment as we have the JS client for that.  

Doughnut signature verification is done as part of the extrinsic check so we can move this issue to cennznet and/or plug

**Comment by holygits** [comment]
Re-opened after clarifying use case
