### ISSUE TITLE
Fn to encode DoughnutV0 payload without signature bytes

### ISSUE THREAD

**Issue by holygits** [cennznet/doughnut-rs#32]
The `payload()` function should return the encoded doughnut minus the signature.
The current implementation encodes and then discards the signature.
Refactor encoding so that there is a version which does not add the signature in order to optimize this.

https://github.com/cennznet/doughnut-rs/blob/0a09486fddf26ac410146d6a17f05b6d270b41ff/src/v0/parity.rs#L50-L53

**Comment by royyang-centrality** [comment]
For internal tracking: https://centralitydev.atlassian.net/browse/BT-106
