### ISSUE TITLE
Optimize payload & signature method

### ISSUE THREAD

**Issue by xlc** [cennznet/doughnut-rs#5]
https://github.com/cennznet/doughnut-rs/blob/0a09486fddf26ac410146d6a17f05b6d270b41ff/src/v0/parity.rs#L50-L58

It does a few unnecessary allocations

**Comment by holygits** [comment]
All of parity codec is un-optimized at the moment. There is an optimized codec in v0/mod.rs

**Comment by xlc** [comment]
why we have optimized version and unoptimized one? I don't understand the structure.

**Comment by holygits** [comment]
One is the ideal codec the other is sadly for compatibility with extrinsics in substrate. I think parity-codec Input trait needs to surface the whole `&[u8]` for us to make use of it

**Comment by holygits** [comment]
superseded by #31
