### ISSUE TITLE
Refactor domain_index

### ISSUE THREAD

**Issue by xlc** [cennznet/doughnut-rs#6]
https://github.com/cennznet/doughnut-rs/blob/0a09486fddf26ac410146d6a17f05b6d270b41ff/src/v0/parity.rs#L30

It can be easily outdated and causing unexpected bug.

Why domains is a `HashMap` if is really just a `Vec<String, Vec<u8>>`?

**Comment by holygits** [comment]
HashMap is unordered, Vec is an implementation detail to preserve ordering of payloads on encoding/decoding.

**Comment by xlc** [comment]
There is no need to use HashMap at all in this case. `Vec<String, Vec<u8>>` is enough.

**Comment by holygits** [comment]
If we use vec only, then we have to do search when querying the doughnut for permission domains.
This may be the solution if we can't integrate hashmap in https://github.com/cennznet/plug-blockchain/pull/15

**Comment by holygits** [comment]
Closed via #8
