### ISSUE TITLE
Ensure consistence types

### ISSUE THREAD

**Issue by xlc** [cennznet/doughnut-rs#7]
https://github.com/cennznet/doughnut-rs/blob/0a09486fddf26ac410146d6a17f05b6d270b41ff/src/v0/parity.rs#L21-L22

Should be using `H256` or better make it generic parameter

**Comment by holygits** [comment]
Can use the data trait for this: https://github.com/cennznet/doughnut-rs/blob/0a09486fddf26ac410146d6a17f05b6d270b41ff/src/v0/parity.rs#L33-L36
